// models/User.ts
import oracledb, { Connection, Result } from "oracledb";

interface IUser {
  id?: number;
  username: string;
  email: string;
}

class User {
  private connection: Connection;

  constructor(connection: Connection) {
    this.connection = connection;
  }

  async createTable(): Promise<void> {
    const sql = `
      CREATE TABLE Users (
        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
        username VARCHAR2(50) NOT NULL,
        email VARCHAR2(50) NOT NULL,
        PRIMARY KEY (id)
      )
    `;
    await this.connection.execute(sql);
  }
}
